version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - my-pg-network
    environment:
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    volumes:
      - ~/data:/var/lib/postgresql/data
    restart: always
networks:
  my-pg-network:
    name: my-pg-networks
    driver: bridge
