version: "3"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-lib:/var/lib/grafana
      - grafana-datasources:/etc/grafana/datasources
      - grafana-dashboards:/etc/grafana/dashboards
      - grafana-plugins:/var/lib/grafana/plugins
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin2023
    ports:
      - 3000:3000
    networks:
      - front
    restart: always
volumes:
  grafana-lib:
  grafana-datasources:
  grafana-dashboards:
  grafana-plugins:
networks:
  front:
